import Head from "next/head";

import HomePage from "../components/HomePage";
import Navbar from "../components/NavBar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <HomePage />
    </div>
  );
}
